### ISSUE TITLE
Не додумалась в задаче 38, что можно группировать выборку по ID

### ISSUE THREAD

**Issue by elushnikova** [iDeBugger/sql-trainer-2#10]
## Описание задачи
- [Ру](https://github.com/iDeBugger/sql-trainer/blob/baf16b15c065a160e6cf531fee26fee61317f8af/src/i18n/resources/ru.json#L74): "Получите топ-5 покупателей, с [наиболей](https://github.com/iDeBugger/sql-trainer/pull/9/files) суммой всех их накладных. Обратите внимание, что для каждого покупателя должна учитываться именно сумма всех его накладных, а не каждая накладная в отдельности."
- [En](https://github.com/iDeBugger/sql-trainer/blob/baf16b15c065a160e6cf531fee26fee61317f8af/src/i18n/resources/en.json#L74): "Select top-5 customers with higher sum of totals of their invoices."

## Проверочный запрос
```sql
select c.first_name, c.last_name, sum(i.total) as sum
from customers c
join invoices i on i.customer_id = c.id
group by c.first_name, c.last_name, c.id
order by sum desc, c.id desc -- запрос не принимается без сортировки по id
limit 5;
```

## Ожидание / реальность
- Реальное поведение: тренажёр принимает результаты запроса только с сортировкой по `customers.id`.
- Ожидаемое поведение: не знаю, можно ли гарантировать порядок выборки данных без подобной сортировки. Если возможно, то хотелось бы, чтобы запрос помечался правильным без неё — она слишком неявная.

Сейчас же запрос без сортировки по `id` помечается некорректным. В результатах есть два клиента с одинаковой суммой накладных — Eduardo и Mark.

<img width="1280" alt="sql-trainer-38-2" src="https://github.com/iDeBugger/sql-trainer/assets/45839055/3f3a7de7-7cae-4bfa-a7a5-d783ee225b42">

<img width="1280" alt="sql-trainer-38-3" src="https://github.com/iDeBugger/sql-trainer/assets/45839055/38dbbd6c-90be-4890-acc1-49ac34983b26">

**Comment by iDeBugger** [comment]
Полагаю, здесь можно убрать просто сортировку из ожидаемого запроса, она явно тут не нужна в задаче

**Comment by elushnikova** [comment]
Оказывается, в [ожидаемом запросе](https://github.com/iDeBugger/sql-trainer/blob/224efdfab67832d52d3cb7d9a2933c866a442ddb/src/assets/tasks/tasks.ts#L322) нет сортировки по ID.

Там есть группировка по ID, что выглядит куда более толковым действием, чем моя группировка по имени клиента, а затем фамилии.

Закрываю issue — тут нет бага. Если подобное недопонимание будет встречаться слишком часто, можно будет подумать о подсказках для неопытных. Ну а пока всегда можно заглянуть в ответы в исходном коде.
