### ISSUE TITLE
Баг: неполное описание в задаче 36

### ISSUE THREAD

**Issue by elushnikova** [iDeBugger/sql-trainer-2#7]
## Описание задачи
[Ру](https://github.com/iDeBugger/sql-trainer/blob/baf16b15c065a160e6cf531fee26fee61317f8af/src/i18n/resources/ru.json#LL72C39-L72C104): "Получите количество альбомов принадлежащих каждому исполнителю."
[En](https://github.com/iDeBugger/sql-trainer/blob/baf16b15c065a160e6cf531fee26fee61317f8af/src/i18n/resources/en.json#LL72C39-L72C83): "Count the number of albums of each artist."

## Проверочный запрос
```sql
select artists.name, COUNT(*)
from artists
join albums on artists.id = albums.artist_id
group by artists.name
order by artists.id; -- без этой сортировки тренажёр не примет результаты запроса
```

## Ожидание / реальность
Реальное поведение: тренажёр принимает результаты запроса только с сортировкой по `artists.id`.
Ожидаемое поведение: не знаю, можно ли гарантировать порядок выборки данных без подобной сортировки. В целом всё выглядит нормально, но тогда стоит указать это требование в описании задачи.

**Comment by iDeBugger** [comment]
Согласен, задеплоится автоматически через минут 5-10
